TRUNCATE TABLE miestnost_typ CASCADE;
SELECT setval('miestnost_typ_id_seq',1,false);
TRUNCATE TABLE miestnost CASCADE;
SELECT setval('miestnost_id_seq',1,false);
INSERT INTO miestnost_typ(nazov) VALUES ('prednáškova sála');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('DE300', 300, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('DE150', 150, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('AB300', 300, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('AB150', 150, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('BC300', 300, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('BC150', 150, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('CD300', 300, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('CD150', 150, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('poslucháreň');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B-401', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E-701', 100, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E-702', 60, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B701', 60, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B704', 100, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C801', 100, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C802', 65, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('učebňa počítačová');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E121', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E121B', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-PC A', 32, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-PC B', 11, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C117A', 24, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C117B', 24, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D-L03A', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D-L03B', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E-131', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-PC', 43, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('CPU-A', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('CPU-C', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('CPU-E', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('CPU-I', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('CPU-K', 12, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D 003', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D 004', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C117', 48, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C119', 22, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C015', 25, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('CPU', 92, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('učebňa');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('DE35', 35, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E-231', 36, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E-515', 30, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C020', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-004B', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-015', 11, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C310', 6, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C019', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('BU03', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C711', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('ŠIP', 21, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A204', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A222', 24, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A224', 8, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A303', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A518', 24, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A806', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('AB35', 35, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B101', 42, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('BC35', 35, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C101', 36, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C201', 40, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C202', 24, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C301', 40, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C517', 45, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C518', 19, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C518A', 18, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C616', 24, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('CD35', 37, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('laboratórium');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D301', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D328', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D330', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D405', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D406', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D422', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D501', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D502', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D516', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D520', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D521', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D601', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D618', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('DS03', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E130', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E133', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E224', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E228', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E323', 14, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E324', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E404', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E405', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E406', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E412', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E607', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E010', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B-223', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B-408', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C-415', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B-P001', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B-P003', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B-P004', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B-P005', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-003', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-016', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-026', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-103', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-104', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-105A', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-106', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-118', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-119A', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A201A', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A202A', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-105B', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T-119B', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B-P002', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('T', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B112', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B121', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C602', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C702', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D519', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D619', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E413', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E416', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E110', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C613', 15, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E125', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D 105', 15, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D 109', 30, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D 113', 15, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C102', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C103', 8, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A201', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A202', 21, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A301', 5, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A302', 5, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A320', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A321', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A324', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A515', 8, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A516', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A709', 5, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A710', 5, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A711', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A801', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B102', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B105', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B106', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B107', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B108', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B110', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B122', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B201', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B202', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B203', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B206', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B302', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B305', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B309', 12, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B327', 11, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B330', 5, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B403', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B418', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B419', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B501', 16, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B502', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B504', 12, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B505', 12, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B516', 18, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B517', 18, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B614', 22, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B615', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B616', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('BS09', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('LVN', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C120', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C121', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C124', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C214', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C302', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C306', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C312', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C313', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C315', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C402', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C417', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C419', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C502', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C601', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C603', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C701', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C025', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C026', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C027', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('posilňovňa');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('POS', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('zasadačka');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D-424', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D 332', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D 124', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('učebňa jazyková');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A615', 24, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('BU01', 40, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('knižnica, učebňa');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D307', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('NE100', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('NE101', 14, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('C022', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('iné použitie');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('BU02', 18, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('bazén');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('PLAV', 40, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('laboratórium výpočtové');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D712', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('D713', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('A217', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('B329', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('lodenica');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('LODEN.KV', 200, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('telocvičňa malá');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('TM', 20, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('kresliareň');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('E123', 10, '', (SELECT currval('miestnost_typ_id_seq')));
INSERT INTO miestnost_typ(nazov) VALUES ('telocvičňa veľká');
INSERT INTO miestnost(nazov, kapacita, poznamka, id_miestnost_typ) VALUES('TV', 20, '', (SELECT currval('miestnost_typ_id_seq')));
