TRUNCATE TABLE pedagog CASCADE; SELECT setval('pedagog_id_seq',1,false);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xkrchniak','Bc. Matej Krchniak','36242@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 1);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 2);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 6);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xliskap3','Bc. Peter Liska','xliskap3@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 1);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 2);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 6);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xpalo','Bc. Dusan Palo','xpalo@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 1);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 2);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 6);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xstevanak','Bc. Samuel Stevanak','xstevanak@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 1);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 2);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 6);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xbucho','Bc. Ondrej Buch','xbucho@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 1);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 2);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 6);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xmikuskap','Bc. Peter Mikuska','xmikuskap@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 1);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 2);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 6);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xkrajcovicv1','Bc. Vladimir Krajcovic','xkrajcovicv1@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 1);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 2);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 6);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xdrahos','Bc. Michal Drahos','xdrahos@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xgrexa','Bc. Jozef Grexa','xgrexa@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xhalama','Bc. Radoslav Halama','xhalama@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xherbst','Bc. Roman Herbst','xherbst@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xmasaryk','Bc. Rastislav Masaryk','xmasaryk@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xkramart','Bc. Tomas Kramar','xkramart@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xpolakovak1','Bc. Katarina Polakova','xpolakovak1@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xmilonova','Bc. Daniela Milonova','xmilonova@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);

--Garanti


insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qbenesova','Dr. Vanda Benesova','63121@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'bielikova','prof. Ing. Maria Bielikova, PhD.','1871@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'bouezzeddine','RNDr. Anna Bou Ezzeddine','bouezzeddine@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'cernansky','Ing. Michal Cernansky, PhD.','cernansky@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'cicak','doc. Ing. Pavel Cicak, PhD.','cicak@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'cipkova','RNDr. Karla Cipkova, PhD.','2149@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'dekysova','JUDr. Iveta Dekysova','iveta.dekysova@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'farkas','prof. Ing. Peter Farkas, DrSc.','farkas@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'galanova','doc. RNDr. Jana Galanova, PhD.','2124@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'gramatova','doc. RNDr. Elena Gramatova, PhD.','gramatova@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'grellnethi','Ing. Igor Grellneth, PhD.','1996@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'grosek','prof. RNDr. Otokar Grosek, PhD.','grosek@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'horvath','prof. Ing. Pavol Horvath, PhD.','horvath@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'hudecj','Ing. Jan Hudec','hudecj@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'hudecl','doc. Ing. Ladislav Hudec, CSc.','hudecl@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'chudad','Mgr. Daniela Chuda, PhD.','38061@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'jancikova','Ing. Edita Jancikova, CSc.','jancikova@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'jelemenska','Ing. Katarina Jelemenska, PhD.','1867@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'jemala','doc. Ing. Lubomir Jemala, PhD.','jemala@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'kapustik','Ing. Ivan Kapustik','kapustik@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'kolesar','prof. Ing. Milan Kolesar, CSc.','2137@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'kotocovam','doc. Ing. Margareta Kotocova, CSc.','2014@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'kotuliak','Ing. Ivan Kotuliak, PhD.','kotuliak@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'kozak','prof. Ing. Stefan Kozak, PhD.','kozak@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'krajcovict','doc. Ing. Tibor Krajcovic, PhD.','1869@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'kukuca','doc. Ing. Peter Kukuca, CSc.','kukuca@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'kvasnicka','prof. Ing. Vladimir Kvasnicka, DrSc.','kvasnicka@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qlaclavik','RNDr. Michal Laclavik, PhD.','qlaclavik@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'miklovic','Mgr. Peter Miklovic','2150@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'mlynarovicm','Ing. Marian Mlynarovic, PhD.','mlynarovicm@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'mlynarovic','doc. Ing. Vladimir Mlynarovic, PhD.','mlynarovic@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'molnar','prof. RNDr. Ludovit Molnar, DrSc.','2145@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'navrat','prof. Ing. Pavol Navrat, PhD.','4660@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'polasek','Ing. Ivan Polasek, PhD.','1426@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'rozinajova','Ing. Viera Rozinajova, PhD.','rozinajova@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qrudolph','Mark Rudolph, PhD.','63120@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'satko','doc. RNDr. Ladislav Satko, PhD.','satko@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'strnad','Ing. Ondrej Strnad, CSc.','strnad@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'soltesova','Mgr. Danica Soltesova, PhD.','soltesova@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'sperka','doc. Ing. Martin Sperka, PhD.','sperka@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'stefanovic','Ing. Juraj Stefanovic, PhD.','stefanovic@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'truchly','Ing. Peter Truchly, PhD.','truchly@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'usak','doc. Ing. Elemir Usak, PhD.','usak@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'vojvoda','Ing. Milan Vojvoda, PhD.','1885@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'vranic','Ing. Valentino Vranic, PhD.','4235@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'ziska','doc. Ing. Milan Ziska, PhD.','ziska@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 3);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);






--Teachers


--Dal som vsetkym pedagogom ze su aj prednasajuci aj cviciaci


insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xabaffy','Ing. Jaroslav Abaffy','30844@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qandrejcikova','Ing. Nadezda Andrejcikova','38835@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'bagala','Ing. Adrian Bagala','38101@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'barla','Ing. Michal Barla','barla@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'bartalosp','Ing. Peter Bartalos','4520@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qbartos','Ing. Pavel Bartos','55461@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'bernatd','Ing. Dusan Bernat','1887@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xburdaf','Bc. Filip Burda','xburdaf@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'cicakova','Ing. Olga Cicakova','cicakova@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'dado','Ing. Boris Dado','1793@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xdobai','Ing. Roland Dobai','xdobai@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xdrahosp','Ing. Peter Drahos','xdrahosp@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'durechova','Ing. Maria Durechova, CSc.','60302@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'flochova','Ing. Jana Flochova, PhD.','flochova@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'galbavy','Ing. Miroslav Galbavy','1936@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qgenci','Ing. Jan Genci, PhD.','71022@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'gnipova','RNDr. Marta Gnipova','120@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xgula','Bc. Stefan Gula','17492@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'habudovan','Mgr. Nikoleta Habudova','52051@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xhavrilap','Bc. Peter Havrila','xhavrilap@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xhirjako','Ing. Ondrej Hirjak','24563@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xhlavatovica','Ing. Adam Hlavatovic','xhlavatovica@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xhuska','Bc. Peter Huska','xhuska@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xjurikovic','Ing. Matej Jurikovic','21950@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xkajsa','Ing. Peter Kajsa','xkajsa@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xkapec','Ing. Peter Kapec','xkapec@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xkasanm','Ing. Michal Kasan','20490@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xkokavecb','Branislav Kokavec, MSc','68084@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'kosik','Ing. Matej Kosik','kosik@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xkovacikt3','Ing. Tomas Kovacik','xkovacikt3@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qkovarovaa','Mgr. Alena Kovarova','38836@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xkuzar','Ing. Tomas Kuzar','30457@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'laca','Ing. Juraj Laca','52470@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'lackop','Ing. Peter Lacko, PhD.','lackop@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qlang','Ing. Jan Lang, PhD.','60247@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xlekavy','Ing. Marian Lekavy, PhD.','xlekavy@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xmagula','Ing. Peter Magula','20888@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xmajtas','Ing. Lubomir Majtas','xmajtas@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qmakula','Ing. Matej Makula','qmakula@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qmarkosova','doc. RNDr. Maria Markosova, PhD.','qmarkosova@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xmatej','Ing. Jan Mate','xmatej@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xmazgutj','Ing. Jakub Mazgut','xmazgutj@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xmederly','Mgr. Pavol Mederly','54689@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xmichalak','Ing. Juraj Michalak','20898@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xmichalecv','Bc. Vladimir Michalec','xmichalecv@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qmilanova','Ing. Zdenka Milanova','qmilanova@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xmisota','Ing. Branislav Misota','10004@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qmitkova','Ing. Veronika Mitkova','qmitkova@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xnosal','Bc. Michal Nosal','17072@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xpalenikt1','Ing. Tomas Palenik','xpalenikt1@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'pancza','Mgr. David Pancza, PhD.','pancza@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qpetrovicp','Mgr. Pavel Petrovic, PhD.','54708@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xpistek','Ing. Peter Pistek','20920@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xpohronska','Ing. Maria Pohronska','xpohronska@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qpolicky','RNDr. Ivan Policky','4282@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'pospichal','prof. RNDr. Jiri Pospichal, DrSc.','1743@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'povazanova','Ing. Anna Povazanova','1825@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'solcany','Ing. Viliam Solcany','1943@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'steinmuller','Ing. Branislav Steinmuller','steinmuller@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xsuchal','Ing. Jan Suchal','xsuchal@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'qseleng','Martin Seleng','qseleng@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'simakova','RNDr. Valeria Simakova','simakova@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xsimkom1','Ing. Marian Simko','30649@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'tomalova','Ing. Elena Tomalova','1826@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xtrebatickyp','Ing. Peter Trebaticky, PhD.','10202@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'tvarozekj','Mgr. Jozef Tvarozek','jozef.tvarozek@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xtvarozek','Ing. Michal Tvarozek','17567@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xvargal','Ing. Lubomir Varga','20970@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xvilhanp','Ing. Peter Vilhan','xvilhanp@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xvojtek','Ing. Peter Vojtek','17569@is.stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);
insert into pedagog (pocet_hodin, login, meno, mail) values(0,'xvrabelm5','Ing. Michal Vrabel','xvrabelm5@stuba.sk');
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 4);
insert into clenstvo (id_pedagog, id_skupina) values ((SELECT currval('pedagog_id_seq')), 5);


-- galbavemu dame vsetky prava

insert into clenstvo (id_pedagog, id_skupina) values ((select id from pedagog where login = 'galbavy'), 1);
insert into clenstvo (id_pedagog, id_skupina) values ((select id from pedagog where login = 'galbavy'), 2);
insert into clenstvo (id_pedagog, id_skupina) values ((select id from pedagog where login = 'galbavy'), 6);