TRUNCATE TABLE predmet CASCADE;
SELECT setval('predmet_id_seq', 1, false);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Matematická logika I', 'ML1_B', 3, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Fyzika', 'FYZ_B', 3, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Telesná kultúra', 'TK_L', 5, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Objektovo-orientované programovanie', 'OOP_B', 1, 3, 4);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Podnikanie a manažment', 'PAM_B', 5, 3, 2);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Pravdepodobnosť a štatistika', 'PAS_B', 5, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Počítačové a komunikačné siete II', 'PKS2_B', 1, 3, 4);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Právo informačných a komunikačných technológií', 'PIKT_B', 3, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Databázové systémy', 'DBS_B', 1, 3, 4);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Bakalársky projekt 0', 'BP0_UISI_B', 3, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Princípy softvérového inžinierstva', 'PSI_B', 1, 3, 4);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Výskumne orientovaný seminár II', 'VOS2_INF_B', 3, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Vývoj programov pre platformu Java', 'VPPJ_B', 5, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Telesná kultúra', 'TK_VYBER_L', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Funkcionálne a logické programovanie', 'FLP_B', 5, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Cudzí jazyk II', 'CJ2_B', 5, 3, 2);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Vývoj webových aplikácií', 'VWEBA_B', 5, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Seminár z anglického jazyka', 'SEMAJ_L_B', 3, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Tvorba efektívnych algoritmov a programov', 'TEAP_B', 5, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Optimalizácia pre informačné a komunikačné technológie', 'OIKT_B', 7, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Umelá inteligencia', 'UI_B', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Maticové algoritmy', 'MALG_B', 5, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Projektovanie aplikácií počítačov', 'PAP_B', 5, 3, 2);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Spoločenské súvislosti informatiky a informačných technológií', 'SSIIT_B', 5, 3, 2);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Matematická analýza II', 'MA2_B', 5, 3, 2);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Záverečná práca', 'ZP_B', 5, 3, 2);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Komunikácia v dejinách kultúry', 'KDK_B', 5, 3, 2);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Bakalársky projekt II', 'BP2_UISI_B', 7, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Webové publikovanie', 'WPUB_B', 7, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Asemblery', 'ASEMBL_B', 5, 3, 1);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Manažment sociálnych systémov', 'MSS_B', 5, 3, 2);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Výberový seminár', 'VYBSEM_B', 5, 3, 2);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('WAN technológie', 'WANT_B', 5, 3, 2);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Bakalársky projekt II', 'BP2_UPSS_B', 5, 3, 2);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Manažment bezpečnosti informačných technológií', 'MBIT_B', 1, 3, 4);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Elektrotechnika', 'ELTCH_B', 5, 3, 2);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Telemetria a prenos údajov', 'TPU_B', 5, 3, 2);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Tvorba softvérových systémov', 'TSS_B', 5, 3, 2);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Kognitívna veda', 'KOGVED_I', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Objavovanie znalostí', 'OZNAL_I', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Algebra', 'ALG_I', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Diplomový projekt I', 'DP1_IS', 3, 3, 4);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Finančný manažment', 'FMAN_I', 1, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Projektovanie', 'PROJ_I', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Tvorba informačného systému v tíme II', 'TIST2_I', 1, 3, 4);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Aplikačné architektúry  softvérových systémov', 'AASS_I', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Stochastické modely', 'STOCHM_I', 1, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Kvalita programových a informačných systémov', 'KPAIS_I', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Bezpečnosť v internete', 'BVI_I', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Evolučné algoritmy', 'EA_I', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Počítačové multimediálne systémy', 'PMS_I', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Grafy', 'GRA_I', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Rétorika', 'RETOR_I', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Distribuované operačné systémy', 'DOS_I', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Odborné praktikum II', 'OP2_UISI', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Štátnicový predmet', 'SP_UISI', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('E-komunikácia obchodných a administratívnych procesov', 'EKOMOAP_I', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Diplomový projekt III', 'DP3_IS', 3, 3, 4);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Diplomový projekt II', 'DP2_IS', 3, 3, 4);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Diplomový projekt I', 'DP1_SI', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Tvorba softvérového systému v tíme II', 'TSST2_I', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Diplomový projekt III', 'DP3_SI', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Diplomový projekt II', 'DP2_SI', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Odborné praktikum I', 'OP1_UISI', 3, 3, 3);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Logické obvody', 'LO_B', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Tímový projekt II', 'TIMP2_I', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Diplomový projekt I', 'DP1_PSS', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Návrh digitálnych systémov', 'NDS_I', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Satelitné systémy', 'SATSYS_I', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Architektúra mobilných sietí', 'AMOBS_I', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Rekonfigurovateľné digitálne systémy', 'RDS_I', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Diagnostika a spoľahlivosť digitálnych systémov', 'DSDS_I', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Odborné praktikum II', 'OP2_UPSS', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Mikropočítače', 'MIKROP_B', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Diplomový projekt III', 'DP3_PSS', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Štátnicový predmet', 'SP_UPSS', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Diplomový projekt II', 'DP2_PSS', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Bakalársky projekt 0', 'BP0_UPSS_B', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Výskumne orientovaný seminár II', 'VOS2_PSS_B', 1, 3, 5);
INSERT INTO predmet(nazov, kod, semester, sposob_ukoncenia, studijny_program) VALUES ('Odborné praktikum I', 'OP1_UPSS', 1, 3, 5);
